import { IBM_Plex_Sans } from "next/font/google";
import { ReactNode } from "react";
import { Metadata } from "next";
import "./normalize.css";
import "./globals.css";
import Header from "@/components/Header/Header";

const IBM = IBM_Plex_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>): JSX.Element {
  return (
    <html lang="en">
      <body className={IBM.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
